<a href="https://colab.research.google.com/github/Anna-Tereshchuk/Data-Engineering-Notebooks/blob/main/Indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy** (скорочено від Numerical Python) є основою числових обчислень у Python. Це потужний інструмент для роботи з масивами даних, який дозволяє виконувати швидкі математичні операції. NumPy інтегрується з Pandas, що робить аналіз даних ще швидшим та ефективнішим.






In [1]:
import numpy as np


**Створення масиву**

In [2]:
array1 = np.array([10, 20, 30, 40, 50])


**Доступ до елементів за індексом:**



> Доступ до другого елемента  (індекс 1, оскільки індексація починається з 0):



In [3]:
second_element = array1[1]
print(second_element)


20




> Доступ до другого з кінця елемента (індекс -2):



In [4]:
second_last_element = array1[-2]
print(second_last_element)


40


**Нарізка (Slicing)**



> Отримання підмасиву з другого по четвертий елемент (індекси 1 до 4, але 4 не включається):



In [5]:
sliced_array = array1[1:4]
print(sliced_array)


[20 30 40]



>Нарізка з кроком (отримання кожного другого елемента):



In [6]:
step_array = array1[::2]
print(step_array)


[10 30 50]


**Індексація та нарізка багатовимірних масивів**



> Створення матриці (2D масиву):



In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Доступ до елементів у матриці:**



> Доступ до елемента у другому рядку та другому стовпці (індекси [1, 1]):



In [8]:
element = matrix[1, 1]
print(element)


5


**Нарізка рядків та стовпців у матриці:**


> Отримання другого рядка:




In [10]:
second_row = matrix[1, :]
print(second_row)  # [4 5 6]


[4 5 6]



> Отримання другого стовпця:



In [11]:
second_column = matrix[:, 1]
print(second_column)  # [2 5 8]


[2 5 8]


**Управління відсутніми даними в NumPy**



> Створення масиву з відсутніми значеннями:



In [12]:
data = np.array([1, 2, 3, np.nan, 4, 5])
print(data)

[ 1.  2.  3. nan  4.  5.]



> Виявлення відсутніх значень



In [13]:
missing = np.isnan(data)
print(missing)

[False False False  True False False]




> Заповнення відсутніх значень:



In [14]:
data_filled = np.nan_to_num(data, nan=100)
print(data_filled)

[  1.   2.   3. 100.   4.   5.]
