<a href="https://colab.research.google.com/github/Anna-Tereshchuk/Data-Engineering-Notebooks/blob/main/NumPy_Linear_algebra_and_statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy** (скорочено від Numerical Python) є основою числових обчислень у Python. Це потужний інструмент для роботи з масивами даних, який дозволяє виконувати швидкі математичні операції. NumPy інтегрується з Pandas, що робить аналіз даних ще швидшим та ефективнішим.






In [18]:
import numpy as np



> Створення двовимірних масивів (матриць):



In [19]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print(array1)
print(array2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


**Множення матриць**


> Використання функції `np.dot` для множення матриць:



In [20]:
mul = np.dot(array1, array2)
print(mul)


[[19 22]
 [43 50]]


**Інверсія матриці**



> Використання функції `np.linalg.inv` для знаходження оберненої матриці:



In [21]:
inv = np.linalg.inv(array1)
print(inv)


[[-2.   1. ]
 [ 1.5 -0.5]]


**Знаходження власних значень та власних векторів:**



> Використання функції `np.linalg.eig` для знаходження власних значень та власних векторів:



In [22]:
eigenvalues, eigenvectors = np.linalg.eig(array1)
print(eigenvalues)
print(eigenvectors)


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**Статистика**


> Створення одновимірного масиву



In [23]:
data = np.array([1, 2, 3, 4, 5])
print(data)

[1 2 3 4 5]


**Обчислення середнього значення:**


> Використання функції `np.mean` для обчислення середнього значення:



In [24]:
mean = np.mean(data)
print(mean)


3.0


**Обчислення стандартного відхилення:**


> Використання функції` np.std` для обчислення стандартного відхилення:



In [25]:
std = np.std(data)
print(std)


1.4142135623730951


**Обчислення коефіцієнта кореляції:**


> Створення другого масиву:




In [26]:
data2 = np.array([11, 12, 13, 14, 15])
print(data2)

[11 12 13 14 15]



> Використання функції `np.corrcoef` для обчислення коефіцієнта кореляції:





In [27]:
corr = np.corrcoef(data, data2)
print(corr)


[[1. 1.]
 [1. 1.]]
