<a href="https://colab.research.google.com/github/Anna-Tereshchuk/Data-Engineering-Notebooks/blob/main/NumPy_Array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy** (скорочено від Numerical Python) є основою числових обчислень у Python. Це потужний інструмент для роботи з масивами даних, який дозволяє виконувати швидкі математичні операції. NumPy інтегрується з Pandas, що робить аналіз даних ще швидшим та ефективнішим.






In [1]:
import numpy as np


**Операції з масивами в NumPy**

**Створення двох масивів:**

In [12]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])


**Додавання масивів:**

In [22]:
sum_array = array1 + array2
print(sum_array)

[ 7  9 11 13 15]


**Віднімання масивів:**

In [23]:
sub_array = array1 - array2
print(sub_array)

[-5 -5 -5 -5 -5]


У Python, коли ви використовуєте бібліотеку NumPy, віднімання масивів працює за принципом елементного обчислення (element-wise operation). Це означає, що для кожного елемента з першого масиву буде відніматися відповідний елемент з другого масиву, і результатом буде новий масив із такими ж розмірами.


> Розміри масивів повинні бути однакові.

Якщо масиви мають різні розміри, буде виникати помилка, оскільки NumPy не зможе виконати операцію елемент за елементом.


> broadcasting
Якщо один з масивів є скалярним (наприклад, число 5), то NumPy застосує це число до кожного елемента другого масиву.


```
array1 - 5  # Результат: [-4 -3 -2 -1  0]

```



> Типи даних
Якщо масиви мають різні типи даних (наприклад, int і float), результат буде приведено до більш загального типу (в даному випадку float)







**Множення масивів**

In [24]:
mul_array = array1 * array2
print(mul_array)

[ 6 14 24 36 50]


**Ділення масивів**

In [25]:
div_array = array1 / array2
print(div_array)


[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


**Агрегаційні функції**





**Середнє значення:**

In [26]:
mean_value = np.mean(array1)
print(mean_value)


3.0


**Сума елементів:**


In [27]:
sum_value = np.sum(array1)
print(sum_value)


15


**Максимальне значення**

In [28]:
max_value = np.max(array1)
print(max_value)


5


**Мінімальне значення**

In [29]:
min_value = np.min(array1)
print(min_value)


1


**Логічні операції**

**Порівняння елементів:**

In [30]:
greater_than_three = array1 > 3
print(greater_than_three)


[False False False  True  True]


**Broadcasting**

NumPy дозволяє виконувати операції над масивами різних форм, автоматично розширюючи їх до сумісних розмірів.