<a href="https://colab.research.google.com/github/Anna-Tereshchuk/Data-Engineering-Notebooks/blob/main/NumPy_Array_creation_and_attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy** (скорочено від Numerical Python) є основою числових обчислень у Python. Це потужний інструмент для роботи з масивами даних, який дозволяє виконувати швидкі математичні операції. NumPy інтегрується з Pandas, що робить аналіз даних ще швидшим та ефективнішим.






In [1]:
import numpy as np


Створення масиву з списку

In [2]:
numbers_list = [1, 2, 3, 4, 5]
array_from_list = np.array(numbers_list)
print(array_from_list)


[1 2 3 4 5]


Створення масиву з нулями

In [3]:
zero_array = np.zeros(5)
print(zero_array)


[0. 0. 0. 0. 0.]


Створення масиву з одиницями

In [4]:
ones_array = np.ones(3)
print(ones_array)


[1. 1. 1.]


Створення масиву з діапазону чисел

In [5]:
range_array = np.arange(1, 10, 2)
print(range_array)


[1 3 5 7 9]


Створення масиву з випадкових цілих чисел

In [6]:
random_array = np.random.randint(1, 100, size=5)
print(random_array)


[56 55 15 67 34]


Створення випадкової матриці

In [7]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.46051405 0.68493935 0.39710755]
 [0.02898574 0.07311606 0.67738276]
 [0.40618293 0.84017578 0.41739525]]


**Атрибути масивів**

Форма масиву

In [8]:
shape = range_array.shape
print(shape)


(5,)


Розмір масиву

In [9]:
size = range_array.size
print(size)


5


Тип даних масиву

In [10]:
dtype = range_array.dtype
print(dtype)


int64


Вимірність масиву

In [11]:
ndim = range_array.ndim
print(ndim)


1
